[2024-05-16 12:40:31,005][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=3, round_timeout=None)
[2024-05-16 12:40:33,250][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:172.16.0.2': 1.0, 'object_store_memory': 3645391257.0, 'CPU': 16.0, 'memory': 7290782516.0}
[2024-05-16 12:40:33,250][flwr][INFO] - Initializing global parameters
[2024-05-16 12:40:33,250][flwr][INFO] - Requesting initial parameters from one random client
[2024-05-16 12:40:34,259][flwr][INFO] - Received initial parameters from one random client
[2024-05-16 12:40:34,259][flwr][INFO] - Evaluating initial parameters
[2024-05-16 12:40:34,915][flwr][INFO] - initial parameters (loss, other metrics): 720.3488512039185, {'accuracy': 0.1198}
[2024-05-16 12:40:34,915][flwr][INFO] - FL starting
[2024-05-16 12:40:34,915][flwr][DEBUG] - fit_round 1: strategy sampled 1 clients (out of 3)
[2024-05-16 12:40:37,731][flwr][DEBUG] - fit_round 1 received 1 results and 0 failures
[2024-05-16 12:40:37,733][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-05-16 12:40:38,360][flwr][INFO] - fit progress: (1, 35.16846325516235, {'accuracy': 0.9653}, 3.4455071780012076)
[2024-05-16 12:40:38,360][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 3)
[2024-05-16 12:40:38,483][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=31839, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:40:39,394][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=31853, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:40:39,395][flwr][DEBUG] - evaluate_round 1 received 0 results and 2 failures
[2024-05-16 12:40:39,395][flwr][DEBUG] - fit_round 2: strategy sampled 1 clients (out of 3)
[2024-05-16 12:40:42,133][flwr][DEBUG] - fit_round 2 received 1 results and 0 failures
[2024-05-16 12:40:42,791][flwr][INFO] - fit progress: (2, 21.39124756703677, {'accuracy': 0.9796}, 7.87578644900168)
[2024-05-16 12:40:42,791][flwr][DEBUG] - evaluate_round 2: strategy sampled 2 clients (out of 3)
[2024-05-16 12:40:42,912][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=31853, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:40:42,913][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=31839, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:40:42,913][flwr][DEBUG] - evaluate_round 2 received 0 results and 2 failures
[2024-05-16 12:40:42,913][flwr][DEBUG] - fit_round 3: strategy sampled 1 clients (out of 3)
[2024-05-16 12:40:45,667][flwr][DEBUG] - fit_round 3 received 1 results and 0 failures
[2024-05-16 12:40:46,276][flwr][INFO] - fit progress: (3, 19.200311778316973, {'accuracy': 0.9797}, 11.361529646001145)
[2024-05-16 12:40:46,276][flwr][DEBUG] - evaluate_round 3: strategy sampled 2 clients (out of 3)
[2024-05-16 12:40:46,384][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=31839, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:40:46,385][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=31853, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:40:46,385][flwr][DEBUG] - evaluate_round 3 received 0 results and 2 failures
[2024-05-16 12:40:46,385][flwr][INFO] - FL finished in 11.470509366001352
[2024-05-16 12:40:46,385][flwr][INFO] - app_fit: losses_distributed []
[2024-05-16 12:40:46,385][flwr][INFO] - app_fit: metrics_distributed_fit {}
[2024-05-16 12:40:46,385][flwr][INFO] - app_fit: metrics_distributed {}
[2024-05-16 12:40:46,385][flwr][INFO] - app_fit: losses_centralized [(0, 720.3488512039185), (1, 35.16846325516235), (2, 21.39124756703677), (3, 19.200311778316973)]
[2024-05-16 12:40:46,386][flwr][INFO] - app_fit: metrics_centralized {'accuracy': [(0, 0.1198), (1, 0.9653), (2, 0.9796), (3, 0.9797)]}
