[2024-05-16 12:39:10,988][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=3, round_timeout=None)
[2024-05-16 12:39:13,238][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:172.16.0.2': 1.0, 'CPU': 16.0, 'object_store_memory': 3655270809.0, 'memory': 7310541620.0}
[2024-05-16 12:39:13,238][flwr][INFO] - Initializing global parameters
[2024-05-16 12:39:13,238][flwr][INFO] - Requesting initial parameters from one random client
[2024-05-16 12:39:14,240][flwr][INFO] - Received initial parameters from one random client
[2024-05-16 12:39:14,240][flwr][INFO] - Evaluating initial parameters
[2024-05-16 12:39:14,894][flwr][INFO] - initial parameters (loss, other metrics): 720.4933269023895, {'accuracy': 0.0955}
[2024-05-16 12:39:14,894][flwr][INFO] - FL starting
[2024-05-16 12:39:14,894][flwr][DEBUG] - fit_round 1: strategy sampled 1 clients (out of 3)
[2024-05-16 12:39:15,091][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=30806, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/ishmam/Documents/Research/Federated Learning/TestFL/client.py", line 42, in fit
    train(self.model, self.train_loader, optim, epochs, self.device)
  File "/home/ishmam/Documents/Research/Federated Learning/TestFL/model.py", line 49, in train
    loop.set_postfix({"loss": round(loss, 3)})
TypeError: type Tensor doesn't define __round__ method
[2024-05-16 12:39:15,091][flwr][DEBUG] - fit_round 1 received 0 results and 1 failures
[2024-05-16 12:39:15,717][flwr][INFO] - fit progress: (1, 720.4933269023895, {'accuracy': 0.0955}, 0.8227525940001215)
[2024-05-16 12:39:15,717][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 3)
[2024-05-16 12:39:15,807][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=30806, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:39:16,755][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=30814, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:39:16,756][flwr][DEBUG] - evaluate_round 1 received 0 results and 2 failures
[2024-05-16 12:39:16,756][flwr][DEBUG] - fit_round 2: strategy sampled 1 clients (out of 3)
[2024-05-16 12:39:16,875][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=30814, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/ishmam/Documents/Research/Federated Learning/TestFL/client.py", line 42, in fit
    train(self.model, self.train_loader, optim, epochs, self.device)
  File "/home/ishmam/Documents/Research/Federated Learning/TestFL/model.py", line 49, in train
    loop.set_postfix({"loss": round(loss, 3)})
TypeError: type Tensor doesn't define __round__ method
[2024-05-16 12:39:16,875][flwr][DEBUG] - fit_round 2 received 0 results and 1 failures
[2024-05-16 12:39:17,500][flwr][INFO] - fit progress: (2, 720.4933269023895, {'accuracy': 0.0955}, 2.6057982170004834)
[2024-05-16 12:39:17,500][flwr][DEBUG] - evaluate_round 2: strategy sampled 2 clients (out of 3)
[2024-05-16 12:39:17,623][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=30806, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:39:17,623][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=30814, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:39:17,624][flwr][DEBUG] - evaluate_round 2 received 0 results and 2 failures
[2024-05-16 12:39:17,624][flwr][DEBUG] - fit_round 3: strategy sampled 1 clients (out of 3)
[2024-05-16 12:39:17,763][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=30814, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/ishmam/Documents/Research/Federated Learning/TestFL/client.py", line 42, in fit
    train(self.model, self.train_loader, optim, epochs, self.device)
  File "/home/ishmam/Documents/Research/Federated Learning/TestFL/model.py", line 49, in train
    loop.set_postfix({"loss": round(loss, 3)})
TypeError: type Tensor doesn't define __round__ method
[2024-05-16 12:39:17,763][flwr][DEBUG] - fit_round 3 received 0 results and 1 failures
[2024-05-16 12:39:18,382][flwr][INFO] - fit progress: (3, 720.4933269023895, {'accuracy': 0.0955}, 3.4875478249996377)
[2024-05-16 12:39:18,382][flwr][DEBUG] - evaluate_round 3: strategy sampled 2 clients (out of 3)
[2024-05-16 12:39:18,491][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=30806, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:39:18,491][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=30814, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:39:18,492][flwr][DEBUG] - evaluate_round 3 received 0 results and 2 failures
[2024-05-16 12:39:18,492][flwr][INFO] - FL finished in 3.5975733080013015
[2024-05-16 12:39:18,492][flwr][INFO] - app_fit: losses_distributed []
[2024-05-16 12:39:18,492][flwr][INFO] - app_fit: metrics_distributed_fit {}
[2024-05-16 12:39:18,492][flwr][INFO] - app_fit: metrics_distributed {}
[2024-05-16 12:39:18,492][flwr][INFO] - app_fit: losses_centralized [(0, 720.4933269023895), (1, 720.4933269023895), (2, 720.4933269023895), (3, 720.4933269023895)]
[2024-05-16 12:39:18,492][flwr][INFO] - app_fit: metrics_centralized {'accuracy': [(0, 0.0955), (1, 0.0955), (2, 0.0955), (3, 0.0955)]}
