[2024-05-16 11:54:07,937][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=3, round_timeout=None)
[2024-05-16 11:54:10,170][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 7246540800.0, 'node:172.16.0.2': 1.0, 'CPU': 16.0, 'object_store_memory': 3623270400.0}
[2024-05-16 11:54:10,171][flwr][INFO] - Initializing global parameters
[2024-05-16 11:54:10,171][flwr][INFO] - Requesting initial parameters from one random client
[2024-05-16 11:54:11,199][flwr][ERROR] - [36mray::launch_and_get_parameters()[39m (pid=20280, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 136, in launch_and_get_parameters
    return maybe_call_get_parameters(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 163, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 283, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
TypeError: get_parameters() got an unexpected keyword argument 'config'
