[2024-05-16 12:43:05,823][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=3, round_timeout=None)
[2024-05-16 12:43:08,070][flwr][INFO] - Flower VCE: Ray initialized with resources: {'object_store_memory': 3640347033.0, 'node:172.16.0.2': 1.0, 'memory': 7280694068.0, 'CPU': 16.0}
[2024-05-16 12:43:08,070][flwr][INFO] - Initializing global parameters
[2024-05-16 12:43:08,070][flwr][INFO] - Requesting initial parameters from one random client
[2024-05-16 12:43:09,087][flwr][INFO] - Received initial parameters from one random client
[2024-05-16 12:43:09,087][flwr][INFO] - Evaluating initial parameters
[2024-05-16 12:43:09,730][flwr][INFO] - initial parameters (loss, other metrics): 722.0562975406647, {'accuracy': 0.111}
[2024-05-16 12:43:09,730][flwr][INFO] - FL starting
[2024-05-16 12:43:09,730][flwr][DEBUG] - fit_round 1: strategy sampled 1 clients (out of 3)
[2024-05-16 12:43:12,480][flwr][DEBUG] - fit_round 1 received 1 results and 0 failures
[2024-05-16 12:43:12,481][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-05-16 12:43:13,126][flwr][INFO] - fit progress: (1, 37.19848114164779, {'accuracy': 0.9646}, 3.395833725000557)
[2024-05-16 12:43:13,126][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 3)
[2024-05-16 12:43:13,232][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=33731, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:43:14,187][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=33729, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:43:14,188][flwr][DEBUG] - evaluate_round 1 received 0 results and 2 failures
[2024-05-16 12:43:14,188][flwr][DEBUG] - fit_round 2: strategy sampled 1 clients (out of 3)
[2024-05-16 12:43:16,934][flwr][DEBUG] - fit_round 2 received 1 results and 0 failures
[2024-05-16 12:43:17,533][flwr][INFO] - fit progress: (2, 35.019090332556516, {'accuracy': 0.963}, 7.802958590000344)
[2024-05-16 12:43:17,533][flwr][DEBUG] - evaluate_round 2: strategy sampled 2 clients (out of 3)
[2024-05-16 12:43:17,654][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=33729, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:43:17,655][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=33731, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:43:17,655][flwr][DEBUG] - evaluate_round 2 received 0 results and 2 failures
[2024-05-16 12:43:17,655][flwr][DEBUG] - fit_round 3: strategy sampled 1 clients (out of 3)
[2024-05-16 12:43:20,373][flwr][DEBUG] - fit_round 3 received 1 results and 0 failures
[2024-05-16 12:43:20,998][flwr][INFO] - fit progress: (3, 21.97674955741968, {'accuracy': 0.9793}, 11.26848543000051)
[2024-05-16 12:43:20,998][flwr][DEBUG] - evaluate_round 3: strategy sampled 2 clients (out of 3)
[2024-05-16 12:43:21,107][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=33731, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:43:21,108][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=33729, ip=172.16.0.2)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 160, in launch_and_evaluate
    return maybe_call_evaluate(
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/client.py", line 205, in maybe_call_evaluate
    return client.evaluate(evaluate_ins)
  File "/home/ishmam/anaconda3/envs/fl/lib/python3.8/site-packages/flwr/client/app.py", line 321, in _evaluate
    results = self.numpy_client.evaluate(parameters, ins.config)  # type: ignore
TypeError: evaluate() takes 2 positional arguments but 3 were given
[2024-05-16 12:43:21,108][flwr][DEBUG] - evaluate_round 3 received 0 results and 2 failures
[2024-05-16 12:43:21,108][flwr][INFO] - FL finished in 11.378517559000102
[2024-05-16 12:43:21,108][flwr][INFO] - app_fit: losses_distributed []
[2024-05-16 12:43:21,109][flwr][INFO] - app_fit: metrics_distributed_fit {}
[2024-05-16 12:43:21,109][flwr][INFO] - app_fit: metrics_distributed {}
[2024-05-16 12:43:21,109][flwr][INFO] - app_fit: losses_centralized [(0, 722.0562975406647), (1, 37.19848114164779), (2, 35.019090332556516), (3, 21.97674955741968)]
[2024-05-16 12:43:21,109][flwr][INFO] - app_fit: metrics_centralized {'accuracy': [(0, 0.111), (1, 0.9646), (2, 0.963), (3, 0.9793)]}
